@echo off
setlocal EnableDelayedExpansion

rem ============================================================================
rem  Digital Twin Earth — Windows Runner
rem  Mirrors run.sh: builds Docker images, writes deploy\.env, manages stack.
rem  Usage: run.bat [mock] [up^|down^|restart^|logs^|status^|build^|clean^|help]
rem ============================================================================

set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%" >nul
set "COMPOSE_FILE=deploy\docker-compose.yml"

rem ─── Parse args (optional `mock` prefix + command) ──────────────────────────
set "MOCK_MODE=false"
set "ARG1=%~1"
set "ARG2=%~2"
set "CMD=up"

if /I "%ARG1%"=="mock" (
    set "MOCK_MODE=true"
    if not "%ARG2%"=="" set "CMD=%ARG2%"
) else (
    if not "%ARG1%"=="" set "CMD=%ARG1%"
)

echo.
echo Digital Twin Earth — Local Runner ^(Windows^)
echo ============================================================
echo.

if /I "%CMD%"=="help"   goto :usage
if /I "%CMD%"=="--help" goto :usage
if /I "%CMD%"=="-h"     goto :usage
if /I "%CMD%"=="up"      goto :do_up
if /I "%CMD%"=="down"    goto :do_down
if /I "%CMD%"=="restart" goto :do_restart
if /I "%CMD%"=="build"   goto :do_build
if /I "%CMD%"=="logs"    goto :do_logs
if /I "%CMD%"=="status"  goto :do_status
if /I "%CMD%"=="clean"   goto :do_clean

echo [X] Unknown command: %CMD%
echo.
goto :usage

rem ============================================================================
:usage
echo Usage: run.bat [mode] [command]
echo.
echo Modes ^(optional^):
echo   mock       Force all feeds to mock/simulated data ^(no internet required^)
echo.
echo Commands:
echo   up         Build images and start all services ^(default^)
echo   down       Stop and remove all containers
echo   restart    Stop then start
echo   logs       Follow logs from all services
echo   status     Show container status
echo   build      Build Docker images only ^(no start^)
echo   clean      Stop containers and remove volumes ^(destructive^)
echo   help       Show this help
echo.
echo Examples:
echo   run.bat up
echo   run.bat mock up
echo   run.bat down
echo.
echo   set MOCK_FLIGHTS_COUNT=20000 ^&^& set MOCK_SHIPS_COUNT=10000 ^&^& run.bat mock up
echo.
echo   set INGESTION_FEED_FLIGHT=opensky ^&^& set INGESTION_FEED_SHIP=aisstream ^&^& ^
set AISSTREAM_API_KEY=your-key ^&^& run.bat up
echo.
echo Environment variables:
echo   MOCK_SEED              Random seed for mock data ^(default: 42^)
echo   MOCK_FLIGHTS_COUNT     Mock aircraft count ^(default: 500^)
echo   MOCK_SHIPS_COUNT       Mock vessel count ^(default: 200^)
echo   MOCK_SATELLITES_COUNT  Mock satellite count ^(default: 100^)
echo   AISSTREAM_API_KEY      AISStream.io key ^(required for real ships^)
echo   OPENSKY_USERNAME       OpenSky username
echo   OPENSKY_PASSWORD       OpenSky password
echo   GATEWAY_API_KEY        Gateway API key ^(default: dev-key^)
goto :end

rem ============================================================================
:check_prereqs
echo [..] Checking prerequisites...
where docker >nul 2>nul
if errorlevel 1 (
    echo [X] Docker not found. Install Docker Desktop:
    echo     https://www.docker.com/products/docker-desktop/
    exit /b 1
)
docker info >nul 2>nul
if errorlevel 1 (
    echo [X] Docker daemon is not running. Start Docker Desktop.
    exit /b 1
)
docker compose version >nul 2>nul
if errorlevel 1 (
    echo [X] Docker Compose v2 not found. Update Docker Desktop.
    exit /b 1
)
echo [OK] Docker, daemon, and Compose v2 detected.
exit /b 0

rem ============================================================================
:write_env_file
rem Determine feed values, mock mode wins.
if /I "%MOCK_MODE%"=="true" (
    set "FEED_FLIGHT=mock"
    set "SHIP_FEED=mock"
    set "SATELLITES_ENABLED_VAL=false"
    set "SPRING_PROFILES_VAL=mock"
) else (
    if "%INGESTION_FEED_FLIGHT%"=="" ( set "FEED_FLIGHT=mock" ) else ( set "FEED_FLIGHT=%INGESTION_FEED_FLIGHT%" )
    if "%INGESTION_FEED_SHIP%"==""   ( set "SHIP_FEED=mock"   ) else ( set "SHIP_FEED=%INGESTION_FEED_SHIP%" )
    if "%SATELLITES_ENABLED%"==""    ( set "SATELLITES_ENABLED_VAL=false" ) else ( set "SATELLITES_ENABLED_VAL=%SATELLITES_ENABLED%" )
    set "SPRING_PROFILES_VAL=%SPRING_PROFILES_ACTIVE%"
)

if "%MOCK_SEED%"==""              set "MOCK_SEED=42"
if "%MOCK_FLIGHTS_COUNT%"==""     set "MOCK_FLIGHTS_COUNT=500"
if "%MOCK_SHIPS_COUNT%"==""       set "MOCK_SHIPS_COUNT=200"
if "%MOCK_SATELLITES_COUNT%"==""  set "MOCK_SATELLITES_COUNT=100"
if "%GATEWAY_API_KEY%"==""        set "GATEWAY_API_KEY=dev-key"

rem Validate AISStream key requirement.
if /I "%SHIP_FEED%"=="aisstream" (
    if "%AISSTREAM_API_KEY%"=="" (
        echo [X] AISSTREAM_API_KEY is required when INGESTION_FEED_SHIP=aisstream
        echo     Get a free key at: https://aisstream.io
        exit /b 1
    )
)

if not exist "deploy" mkdir "deploy"

(
    echo # Auto-generated by run.bat — do not commit
    echo AISSTREAM_API_KEY=%AISSTREAM_API_KEY%
    echo OPENSKY_USERNAME=%OPENSKY_USERNAME%
    echo OPENSKY_PASSWORD=%OPENSKY_PASSWORD%
    echo GATEWAY_API_KEY=%GATEWAY_API_KEY%
    echo INGESTION_FEED_FLIGHT=%FEED_FLIGHT%
    echo INGESTION_FEED_SHIP=%SHIP_FEED%
    echo SATELLITES_ENABLED=%SATELLITES_ENABLED_VAL%
    echo SPRING_PROFILES_ACTIVE=%SPRING_PROFILES_VAL%
    echo MOCK_SEED=%MOCK_SEED%
    echo MOCK_FLIGHTS_COUNT=%MOCK_FLIGHTS_COUNT%
    echo MOCK_SHIPS_COUNT=%MOCK_SHIPS_COUNT%
    echo MOCK_SATELLITES_COUNT=%MOCK_SATELLITES_COUNT%
) > "deploy\.env"

echo [OK] Environment written to deploy\.env

if /I "%MOCK_MODE%"=="true" (
    echo      Mode: mock ^(deterministic, no internet required^)
    echo      Flights:    %MOCK_FLIGHTS_COUNT% aircraft  ^(seed %MOCK_SEED%^)
    echo      Ships:      %MOCK_SHIPS_COUNT% vessels   ^(seed %MOCK_SEED%^)
    echo      Satellites: %MOCK_SATELLITES_COUNT% mock satellites
) else (
    echo      Flights:    %FEED_FLIGHT%
    echo      Ships:      %SHIP_FEED%
    echo      Satellites: %SATELLITES_ENABLED_VAL%
)
exit /b 0

rem ============================================================================
:build_images
echo.
echo [..] Building Docker images ^(may take several minutes on first build^)...
docker compose -f "%COMPOSE_FILE%" build --parallel
if errorlevel 1 (
    echo [X] Image build failed.
    exit /b 1
)
echo [OK] All images built.
exit /b 0

rem ============================================================================
:start_services
echo.
echo [..] Starting services...
docker compose -f "%COMPOSE_FILE%" up -d
if errorlevel 1 (
    echo [X] docker compose up failed.
    exit /b 1
)

echo.
echo [..] Waiting up to 120s for services to start...
set /a ELAPSED=0
:wait_loop
if %ELAPSED% GEQ 120 goto :wait_done
timeout /t 5 /nobreak >nul
set /a ELAPSED+=5
echo      ^(%ELAPSED%s elapsed^)
goto :wait_loop
:wait_done

echo.
docker compose -f "%COMPOSE_FILE%" ps
echo.
echo [OK] Digital Twin Earth is running!
echo.
echo   Frontend:  http://localhost:4200
echo   API:       http://localhost:8080/api/flights
echo   Health:    http://localhost:8080/actuator/health
echo.
echo   Stream test:
echo     curl -H "X-Api-Key: dev-key" http://localhost:8080/api/stream/flights
echo.
echo   Follow logs: run.bat logs
echo   Stop:        run.bat down
exit /b 0

rem ============================================================================
:stop_services
echo [..] Stopping services...
docker compose -f "%COMPOSE_FILE%" down
if errorlevel 1 exit /b 1
echo [OK] All services stopped.
exit /b 0

rem ============================================================================
:do_up
call :check_prereqs   || goto :failure
call :write_env_file  || goto :failure
call :build_images    || goto :failure
call :start_services  || goto :failure
goto :end

:do_down
call :stop_services || goto :failure
goto :end

:do_restart
call :stop_services   || goto :failure
call :check_prereqs   || goto :failure
call :write_env_file  || goto :failure
call :start_services  || goto :failure
goto :end

:do_build
call :check_prereqs   || goto :failure
call :write_env_file  || goto :failure
call :build_images    || goto :failure
goto :end

:do_logs
docker compose -f "%COMPOSE_FILE%" logs -f --tail=100
goto :end

:do_status
docker compose -f "%COMPOSE_FILE%" ps
goto :end

:do_clean
echo [!] This will REMOVE all containers, networks, AND volumes ^(database data^)!
set /p "CONFIRM=Are you sure? (y/N) "
if /I "%CONFIRM%"=="y" (
    docker compose -f "%COMPOSE_FILE%" down -v --remove-orphans
    echo [OK] Cleaned up.
) else (
    echo [..] Cancelled.
)
goto :end

rem ============================================================================
:failure
popd >nul
endlocal
exit /b 1

:end
popd >nul
endlocal
exit /b 0
