#include "core/ScriptEngine.h"

#include <cstdlib>
#include <sstream>

namespace aurora::core {

void MacroRecorder::start() { recording_ = true; }
void MacroRecorder::stop() { recording_ = false; }

void MacroRecorder::record(const std::string& verb, std::vector<std::string> args) {
  if (!recording_) return;
  actions_.push_back({verb, std::move(args)});
}

std::string MacroRecorder::toPython() const {
  std::ostringstream o;
  o << "# Auto-generated by aurora-eda macro recorder\n";
  o << "import aurora\n\n";
  o << "def replay(view):\n";
  if (actions_.empty()) {
    o << "    pass\n";
    return o.str();
  }
  for (const auto& a : actions_) {
    o << "    view." << a.verb << "(";
    bool first = true;
    for (const auto& arg : a.args) {
      if (!first) o << ", ";
      o << arg;
      first = false;
    }
    o << ")\n";
  }
  return o.str();
}

void ScriptedUiRegistry::registerItem(ScriptedMenuItem item) {
  items_.push_back(std::move(item));
}

void CustomRuleRegistry::registerRule(ScriptedRule rule) {
  rules_.push_back(std::move(rule));
}

std::vector<ScriptedRule> CustomRuleRegistry::rulesByKind(const std::string& kind) const {
  std::vector<ScriptedRule> out;
  for (const auto& r : rules_) if (r.kind == kind) out.push_back(r);
  return out;
}

int BatchRunner::run(const BatchOptions& opts) {
  std::ostringstream cmd;
  cmd << "python \"" << opts.scriptPath.string() << "\"";
  for (const auto& [k, v] : opts.args) cmd << " --" << k << "=" << v;
  if (opts.exportResults && !opts.resultsDir.empty()) {
    cmd << " --results-dir=\"" << opts.resultsDir.string() << "\"";
  }
  return std::system(cmd.str().c_str());
}

}  // namespace aurora::core
